/* 
   SCRIPT 3/4 : VUES
   Ce fichier contient toutes les vues pour faciliter les requetes et le reporting.
   A executer apres 02_FONCTIONS_PROCEDURES.sql
*/

/* ====================== VUES LOCATAIRES ====================== */

/* Vue des locataires avec leur statut calcule: ACTIF, ANCIEN ou PROSPECT */
CREATE OR REPLACE VIEW V_LOCATAIRES_STATUT AS
SELECT 
    l.ID_LOCATAIRE, 
    l.NOM_LOC, 
    l.PRENOM_LOC, 
    l.TEL_LOC, 
    l.MAIL_LOC, 
    l.DATE_NAISSANCE,
    CASE 
        WHEN EXISTS (
            SELECT 1 FROM SIGNE s 
            JOIN BAIL b ON s.ID_BAIL = b.ID_BAIL
            WHERE s.ID_LOCATAIRE = l.ID_LOCATAIRE 
            AND b.ETAT = 'EN_COURS'
        ) THEN 'ACTIF'
        WHEN EXISTS (
            SELECT 1 FROM SIGNE s 
            WHERE s.ID_LOCATAIRE = l.ID_LOCATAIRE
        ) THEN 'ANCIEN'
        ELSE 'PROSPECT'
    END AS STATUT,
    CASE 
        WHEN EXISTS (
            SELECT 1 FROM SIGNE s 
            JOIN BAIL b ON s.ID_BAIL = b.ID_BAIL
            WHERE s.ID_LOCATAIRE = l.ID_LOCATAIRE 
            AND b.ETAT = 'EN_COURS'
        ) THEN 'Oui' 
        ELSE 'Non' 
    END AS ACTUEL
FROM LOCATAIRE l;
/

/* ====================== VUES LOGEMENTS ====================== */

/* Vue des logements avec statut de disponibilite et adresse complete */
CREATE OR REPLACE VIEW V_LOGEMENTS_STATUT AS
SELECT 
    l.ID_LOGEMENT, 
    l.ADRESSE_LOGEMENT,
    l.TYPE_LOGEMENT, 
    l.SURFACE, 
    l.NB_PIECES, 
    l.NUM_FISCAL,
    l.ID_BATIMENT, 
    l.ID_BAIL,
    CASE WHEN l.ID_BAIL IS NULL THEN 'Disponible' ELSE 'Loue' END AS STATUT,
    b.ADRESSE AS ADRESSE_BATIMENT,
    b.CODE_POSTALE,
    b.ADRESSE || ' - ' || b.CODE_POSTALE AS ADRESSE_COMPLETE
FROM LOGEMENT l 
LEFT JOIN BATIMENT b ON l.ID_BATIMENT = b.ID_BATIMENT;
/

/* ====================== VUES GARAGES ====================== */

/* Vue des garages avec statut et nom du locataire si loue */
CREATE OR REPLACE VIEW V_GARAGES_STATUT AS
SELECT 
    g.ID_GARAGE, 
    g.ADRESSE_GARAGE,
    g.SURFACE_GARAGE, 
    g.NUM_FISCAL, 
    g.ID_BATIMENT, 
    g.ID_LOGEMENT, 
    g.ID_BAIL,
    CASE WHEN g.ID_BAIL IS NULL THEN 'Disponible' ELSE 'Loue' END AS STATUT,
    b.ADRESSE AS ADRESSE_BATIMENT,
    b.CODE_POSTALE,
    b.ADRESSE || ' - ' || b.CODE_POSTALE AS ADRESSE_COMPLETE,
    (SELECT loc.NOM_LOC || ' ' || loc.PRENOM_LOC 
     FROM SIGNE s 
     JOIN LOCATAIRE loc ON s.ID_LOCATAIRE = loc.ID_LOCATAIRE
     WHERE s.ID_BAIL = g.ID_BAIL AND ROWNUM = 1) AS LOCATAIRE
FROM GARAGE g 
LEFT JOIN BATIMENT b ON g.ID_BATIMENT = b.ID_BATIMENT;
/

/* ====================== VUE BAUX COMPLETS ====================== */

/* Vue denormalisee des baux avec locataire, logement et batiment */
CREATE OR REPLACE VIEW V_BAUX_COMPLETS AS
SELECT 
    b.ID_BAIL,
    b.DATE_DEBUT,
    b.DATE_FIN,
    b.LOYER_INITIAL,
    b.PROVISION_INITIALES,
    b.CAUTION,
    b.ETAT,
    b.JOUR_PAIEMENT,
    b.SOLDE_TOUT_COMPTE,
    (SELECT l.NOM_LOC || ' ' || l.PRENOM_LOC
     FROM SIGNE s JOIN LOCATAIRE l ON s.ID_LOCATAIRE = l.ID_LOCATAIRE
     WHERE s.ID_BAIL = b.ID_BAIL AND ROWNUM = 1) AS LOCATAIRE_PRINCIPAL,
    (SELECT l.ID_LOCATAIRE
     FROM SIGNE s JOIN LOCATAIRE l ON s.ID_LOCATAIRE = l.ID_LOCATAIRE
     WHERE s.ID_BAIL = b.ID_BAIL AND ROWNUM = 1) AS ID_LOCATAIRE,
    (SELECT lo.ID_LOGEMENT FROM LOGEMENT lo WHERE lo.ID_BAIL = b.ID_BAIL AND ROWNUM = 1) AS ID_LOGEMENT,
    (SELECT lo.TYPE_LOGEMENT FROM LOGEMENT lo WHERE lo.ID_BAIL = b.ID_BAIL AND ROWNUM = 1) AS TYPE_LOGEMENT,
    (SELECT bat.ADRESSE FROM LOGEMENT lo JOIN BATIMENT bat ON lo.ID_BATIMENT = bat.ID_BATIMENT 
     WHERE lo.ID_BAIL = b.ID_BAIL AND ROWNUM = 1) AS ADRESSE_LOGEMENT,
    (SELECT lo.ID_BATIMENT FROM LOGEMENT lo WHERE lo.ID_BAIL = b.ID_BAIL AND ROWNUM = 1) AS ID_BATIMENT,
    (SELECT COUNT(*) FROM GARAGE g WHERE g.ID_BAIL = b.ID_BAIL) AS NB_GARAGES
FROM BAIL b;
/

/* ====================== VUE QUITTANCES ====================== */

/* Vue des quittances de loyer avec infos locataire pour generation PDF */
CREATE OR REPLACE VIEW V_QUITTANCES_LOCATAIRE AS
SELECT 
    l.ID_LOYER,
    l.ID_BAIL,
    l.MOIS,
    l.MONTANT_LOYER,
    l.MONTANT_PROVISION,
    l.MONTANT_LOYER + NVL(l.MONTANT_PROVISION, 0) AS TOTAL,
    l.STATUT,
    l.DATE_PAIEMENT,
    l.QUITTANCE,
    loc.ID_LOCATAIRE,
    loc.NOM_LOC,
    loc.PRENOM_LOC,
    loc.NOM_LOC || ' ' || loc.PRENOM_LOC AS NOM_COMPLET
FROM LOYER l
JOIN BAIL b ON l.ID_BAIL = b.ID_BAIL
JOIN SIGNE s ON b.ID_BAIL = s.ID_BAIL
JOIN LOCATAIRE loc ON s.ID_LOCATAIRE = loc.ID_LOCATAIRE;
/

/* ====================== VUE CAUTION ====================== */

/* Vue du suivi des cautions avec mouvements agreges */
CREATE OR REPLACE VIEW V_CAUTION_LOCATAIRE AS
SELECT 
    b.ID_BAIL,
    b.CAUTION AS MONTANT_CAUTION,
    loc.ID_LOCATAIRE,
    loc.NOM_LOC,
    loc.PRENOM_LOC,
    loc.NOM_LOC || ' ' || loc.PRENOM_LOC AS NOM_COMPLET,
    (SELECT SUM(mc.MONTANT) FROM MOUVEMENT_CAUTION mc 
     WHERE mc.ID_BAIL = b.ID_BAIL AND mc.TYPE_MOUVEMENT = 'Versement') AS TOTAL_VERSE,
    (SELECT SUM(mc.MONTANT) FROM MOUVEMENT_CAUTION mc 
     WHERE mc.ID_BAIL = b.ID_BAIL AND mc.TYPE_MOUVEMENT = 'Restitution') AS TOTAL_RESTITUE,
    (SELECT SUM(mc.MONTANT) FROM MOUVEMENT_CAUTION mc 
     WHERE mc.ID_BAIL = b.ID_BAIL AND mc.TYPE_MOUVEMENT = 'Retenue') AS TOTAL_RETENU
FROM BAIL b
JOIN SIGNE s ON b.ID_BAIL = s.ID_BAIL
JOIN LOCATAIRE loc ON s.ID_LOCATAIRE = loc.ID_LOCATAIRE;
/

/* ====================== VUE DIAGNOSTICS ====================== */

/* Vue des diagnostics avec statut de validite (alerte si expire bientot) */
CREATE OR REPLACE VIEW V_DIAGNOSTICS_LOCATAIRE AS
SELECT 
    d.ID_DIAGNOSTIQUE,
    d.TYPE_DIAG,
    d.DATE_EMISSION,
    d.DATE_EXPIRATION,
    d.REFERENCE,
    d.ID_LOGEMENT,
    l.TYPE_LOGEMENT,
    l.ID_BAIL,
    CASE 
        WHEN d.DATE_EXPIRATION < SYSDATE THEN 'Expire'
        WHEN d.DATE_EXPIRATION < SYSDATE + 90 THEN 'Expire bientot'
        ELSE 'Valide'
    END AS STATUT_VALIDITE
FROM DIAGNOSTIQUE d
JOIN LOGEMENT l ON d.ID_LOGEMENT = l.ID_LOGEMENT;
/

/* ====================== VUE INDEX COMPTEUR ====================== */

/* Vue des releves de compteur avec calcul de consommation */
CREATE OR REPLACE VIEW V_INDEX_LOCATAIRE AS
SELECT 
    r.ID_RELEVE,
    r.TYPE,
    r.UNITE,
    r.NUM_COMPTEUR,
    r.ANCIEN_INDEX,
    r.NOUVELLE_INDEX,
    r.NOUVELLE_INDEX - NVL(r.ANCIEN_INDEX, 0) AS CONSOMMATION,
    r.DATE_,
    l.ID_LOGEMENT,
    l.ID_BAIL,
    'LOGEMENT' AS SOURCE
FROM RELEVE_COMPTEUR r
JOIN LOGEMENT l ON r.ID_RELEVE = l.ID_RELEVE
UNION ALL
SELECT 
    r.ID_RELEVE,
    r.TYPE,
    r.UNITE,
    r.NUM_COMPTEUR,
    r.ANCIEN_INDEX,
    r.NOUVELLE_INDEX,
    r.NOUVELLE_INDEX - NVL(r.ANCIEN_INDEX, 0) AS CONSOMMATION,
    r.DATE_,
    NULL AS ID_LOGEMENT,
    g.ID_BAIL,
    'GARAGE' AS SOURCE
FROM RELEVE_COMPTEUR r
JOIN GARAGE g ON r.ID_RELEVE = g.ID_RELEVE;
/

/* Vue des releves lies directement aux garages */
CREATE OR REPLACE VIEW V_RELEVES_GARAGE AS
SELECT 
    r.ID_RELEVE,
    r.TYPE,
    r.UNITE,
    r.NUM_COMPTEUR,
    r.ANCIEN_INDEX,
    r.NOUVELLE_INDEX,
    r.NOUVELLE_INDEX - NVL(r.ANCIEN_INDEX, 0) AS CONSOMMATION,
    r.DATE_,
    g.ID_GARAGE,
    g.ADRESSE_GARAGE,
    g.ID_BAIL
FROM RELEVE_COMPTEUR r
JOIN GARAGE g ON r.ID_RELEVE = g.ID_RELEVE;
/

/* ====================== VUES ASSURANCES ====================== */

/* Vue des assurances par logement */
CREATE OR REPLACE VIEW V_ASSURANCES_LOGEMENT AS
SELECT 
    a.NUMASSURANCE,
    a.TYPE,
    a.PRIMEBASE,
    a.NOM_COMPAGNIE,
    a.DATE_EFFET,
    a.ID_LOGEMENT,
    l.TYPE_LOGEMENT,
    l.ADRESSE_LOGEMENT,
    l.ID_BAIL
FROM ASSURANCE a
JOIN LOGEMENT l ON a.ID_LOGEMENT = l.ID_LOGEMENT
WHERE a.ID_LOGEMENT IS NOT NULL;
/

/* Vue des assurances par garage */
CREATE OR REPLACE VIEW V_ASSURANCES_GARAGE AS
SELECT 
    a.NUMASSURANCE,
    a.TYPE,
    a.PRIMEBASE,
    a.NOM_COMPAGNIE,
    a.DATE_EFFET,
    a.ID_GARAGE,
    g.ADRESSE_GARAGE,
    g.ID_BAIL
FROM ASSURANCE a
JOIN GARAGE g ON a.ID_GARAGE = g.ID_GARAGE
WHERE a.ID_GARAGE IS NOT NULL;
/

/* ====================== VUES TABLEAU DE BORD ====================== */

/* Vue des statistiques globales pour la page d'accueil */
CREATE OR REPLACE VIEW V_TABLEAU_BORD_STATS AS
SELECT 
    (SELECT COUNT(*) FROM LOGEMENT) AS NB_LOGEMENTS,
    (SELECT COUNT(*) FROM GARAGE) AS NB_GARAGES,
    (SELECT COUNT(*) FROM LOGEMENT) + (SELECT COUNT(*) FROM GARAGE) AS NB_PROPRIETES,
    (SELECT COUNT(*) FROM LOGEMENT WHERE ID_BAIL IS NOT NULL) AS NB_LOGEMENTS_LOUES,
    (SELECT COUNT(*) FROM GARAGE WHERE ID_BAIL IS NOT NULL) AS NB_GARAGES_LOUES,
    (SELECT COUNT(*) FROM LOCATAIRE) AS NB_LOCATAIRES_TOTAL,
    (SELECT COUNT(DISTINCT s.ID_LOCATAIRE) FROM SIGNE s 
     JOIN BAIL b ON s.ID_BAIL = b.ID_BAIL WHERE b.ETAT = 'EN_COURS') AS NB_LOCATAIRES_ACTIFS,
    (SELECT COUNT(*) FROM BAIL WHERE ETAT = 'EN_COURS') AS NB_BAUX_ACTIFS,
    (SELECT NVL(SUM(LOYER_INITIAL), 0) FROM BAIL WHERE ETAT = 'EN_COURS') AS REVENU_MENSUEL,
    (SELECT NVL(SUM(LOYER_INITIAL * 12), 0) FROM BAIL WHERE ETAT = 'EN_COURS') AS REVENU_ANNUEL
FROM DUAL;
/

/* Vue des proprietes recentes pour affichage rapide */
CREATE OR REPLACE VIEW V_PROPRIETES_RECENTES AS
SELECT * FROM (
    SELECT 
        'LOGEMENT' AS TYPE_BIEN,
        ID_LOGEMENT AS ID_BIEN,
        TYPE_LOGEMENT AS DESCRIPTION,
        ADRESSE_LOGEMENT AS ADRESSE,
        ID_BATIMENT,
        CASE WHEN ID_BAIL IS NULL THEN 'Disponible' ELSE 'Loue' END AS STATUT
    FROM LOGEMENT
    UNION ALL
    SELECT 
        'GARAGE' AS TYPE_BIEN,
        ID_GARAGE AS ID_BIEN,
        'Garage' AS DESCRIPTION,
        ADRESSE_GARAGE AS ADRESSE,
        ID_BATIMENT,
        CASE WHEN ID_BAIL IS NULL THEN 'Disponible' ELSE 'Loue' END AS STATUT
    FROM GARAGE
)
ORDER BY ID_BIEN DESC;
/

/* ====================== VUE ACTIVITES RECENTES ====================== */

/* Vue combinant toutes les activites des 30 derniers jours pour le dashboard */
CREATE OR REPLACE VIEW V_ACTIVITES_RECENTES AS
SELECT * FROM (
    SELECT 
        'PAIEMENT' AS TYPE_ACTIVITE,
        'Paiement recu : ' || l.MONTANT_LOYER || ' EUR' AS DESCRIPTION,
        l.DATE_PAIEMENT AS DATE_ACTIVITE,
        l.ID_BAIL AS ID_REFERENCE
    FROM LOYER l
    WHERE UPPER(l.STATUT) = 'PAYE'
    AND l.DATE_PAIEMENT >= SYSDATE - 30
    
    UNION ALL
    
    SELECT 
        'NOUVEAU_BAIL' AS TYPE_ACTIVITE,
        'Nouveau bail signe' AS DESCRIPTION,
        b.DATE_DEBUT AS DATE_ACTIVITE,
        b.ID_BAIL AS ID_REFERENCE
    FROM BAIL b
    WHERE b.DATE_DEBUT >= SYSDATE - 30
    
    UNION ALL
    
    SELECT 
        'FIN_BAIL' AS TYPE_ACTIVITE,
        'Bail termine' AS DESCRIPTION,
        b.DATE_FIN AS DATE_ACTIVITE,
        b.ID_BAIL AS ID_REFERENCE
    FROM BAIL b
    WHERE b.ETAT IN ('RESILIE', 'CLOTURE')
    AND b.DATE_FIN >= SYSDATE - 30
    
    UNION ALL
    
    SELECT 
        'NOUVELLE_FACTURE' AS TYPE_ACTIVITE,
        'Facture : ' || f.NATURE || ' - ' || f.MONTANT_TTC || ' EUR' AS DESCRIPTION,
        f.DATE_EMISSION AS DATE_ACTIVITE,
        f.ID_FACTURE AS ID_REFERENCE
    FROM FACTURE f
    WHERE f.DATE_EMISSION >= SYSDATE - 30
    
    UNION ALL
    
    SELECT 
        'NOUVEAU_LOGEMENT' AS TYPE_ACTIVITE,
        'Nouveau logement : ' || NVL(l.TYPE_LOGEMENT, 'Logement') || ' - ' || l.ADRESSE_LOGEMENT AS DESCRIPTION,
        SYSDATE AS DATE_ACTIVITE,
        l.ID_LOGEMENT AS ID_REFERENCE
    FROM LOGEMENT l
    WHERE l.ID_LOGEMENT >= (SELECT NVL(MAX(ID_LOGEMENT), 0) - 10 FROM LOGEMENT)
    AND ROWNUM <= 5
    
    UNION ALL
    
    SELECT 
        'NOUVEAU_GARAGE' AS TYPE_ACTIVITE,
        'Nouveau garage : ' || g.ADRESSE_GARAGE AS DESCRIPTION,
        SYSDATE AS DATE_ACTIVITE,
        g.ID_GARAGE AS ID_REFERENCE
    FROM GARAGE g
    WHERE g.ID_GARAGE >= (SELECT NVL(MAX(ID_GARAGE), 0) - 10 FROM GARAGE)
    AND ROWNUM <= 5
    
    UNION ALL
    
    SELECT 
        'NOUVEAU_LOCATAIRE' AS TYPE_ACTIVITE,
        'Nouveau locataire : ' || loc.NOM_LOC || ' ' || loc.PRENOM_LOC AS DESCRIPTION,
        SYSDATE AS DATE_ACTIVITE,
        loc.ID_LOCATAIRE AS ID_REFERENCE
    FROM LOCATAIRE loc
    WHERE loc.ID_LOCATAIRE >= (SELECT NVL(MAX(ID_LOCATAIRE), 0) - 10 FROM LOCATAIRE)
    AND ROWNUM <= 5
    
    UNION ALL
    
    SELECT 
        'NOUVELLE_CHARGE' AS TYPE_ACTIVITE,
        'Charge : ' || c.NATURE || ' - ' || c.MONTANT || ' EUR' AS DESCRIPTION,
        c.DATE_CHARGE AS DATE_ACTIVITE,
        c.ID_CHARGE AS ID_REFERENCE
    FROM CHARGES c
    WHERE c.DATE_CHARGE >= SYSDATE - 30
)
WHERE DATE_ACTIVITE IS NOT NULL
ORDER BY DATE_ACTIVITE DESC;
/

/* ====================== VUE RECAP FISCAL ====================== */

/* Vue du recap fiscal annuel par batiment */
CREATE OR REPLACE VIEW V_RECAP_FISCAL_ANNUEL AS
SELECT 
    b.ID_BATIMENT,
    b.ADRESSE,
    b.CODE_POSTALE,
    EXTRACT(YEAR FROM SYSDATE) AS ANNEE,
    getRecapFiscal(b.ID_BATIMENT, EXTRACT(YEAR FROM SYSDATE)) AS RESULTAT_FISCAL,
    (SELECT COUNT(*) FROM LOGEMENT l WHERE l.ID_BATIMENT = b.ID_BATIMENT) AS NB_LOGEMENTS,
    (SELECT COUNT(*) FROM GARAGE g WHERE g.ID_BATIMENT = b.ID_BATIMENT) AS NB_GARAGES
FROM BATIMENT b
ORDER BY b.ID_BATIMENT;
/

/* ====================== VUE STATISTIQUES LOYERS ====================== */

/* Vue combinant les loyers actifs et archives pour les statistiques
   Utilise COMPLEMENT_ADRESSE (corrige depuis ADRESSE_COMPLEMENTAIRE) */
CREATE OR REPLACE VIEW V_STATISTIQUES_LOYERS AS
SELECT 
    l.ID_BAIL,
    NVL(log.TYPE_LOGEMENT, 'Logement') || ' ' || NVL(log.COMPLEMENT_ADRESSE, log.ADRESSE_LOGEMENT) AS NOM_BIEN,
    NVL(log.ID_BATIMENT, g.ID_BATIMENT) AS ID_BATIMENT,
    l.MOIS,
    TO_NUMBER(SUBSTR(TRIM(l.MOIS), 4, 4)) AS ANNEE,
    CASE WHEN UPPER(l.STATUT) = 'PAYE' THEN l.MONTANT_LOYER ELSE 0 END AS LOYER_PAYE,
    CASE WHEN UPPER(l.STATUT) = 'PAYE' THEN NVL(l.MONTANT_PROVISION, 0) ELSE 0 END AS PROVISION_PAYEE,
    'EN_COURS' AS SOURCE
FROM LOYER l
JOIN BAIL b ON l.ID_BAIL = b.ID_BAIL
LEFT JOIN LOGEMENT log ON log.ID_BAIL = b.ID_BAIL
LEFT JOIN GARAGE g ON g.ID_BAIL = b.ID_BAIL AND log.ID_LOGEMENT IS NULL
WHERE b.ETAT != 'CLOTURE'

UNION ALL

SELECT 
    h.ID_BAIL,
    h.NOM_BIEN,
    h.ID_BATIMENT,
    h.MOIS,
    h.ANNEE,
    h.MONTANT_LOYER AS LOYER_PAYE,
    NVL(h.MONTANT_PROVISION, 0) AS PROVISION_PAYEE,
    'ARCHIVE' AS SOURCE
FROM HISTORIQUE_LOYERS h;
/

/* ====================== VUES TRAVAUX PAR ENTREPRISE (NOUVEAU) ====================== */

/* Vue des travaux par entreprise pour un logement - utile pour le suivi des prestataires */
CREATE OR REPLACE VIEW V_TRAVAUX_PAR_ENTREPRISE_LOGEMENT AS
SELECT 
    f.ID_LOGEMENT,
    l.ADRESSE_LOGEMENT,
    e.NOM_ENTREPRISE,
    e.SIRET,
    EXTRACT(YEAR FROM f.DATE_EMISSION) AS ANNEE,
    SUM(f.MONTANT_TTC) AS TOTAL_TRAVAUX
FROM FACTURE f
JOIN ENTREPRISE e ON f.SIRET = e.SIRET
LEFT JOIN LOGEMENT l ON f.ID_LOGEMENT = l.ID_LOGEMENT
WHERE f.TRAVAUX IS NOT NULL OR f.DEDUCTIBLE_IMPOT = 1
GROUP BY f.ID_LOGEMENT, l.ADRESSE_LOGEMENT, e.NOM_ENTREPRISE, e.SIRET, 
         EXTRACT(YEAR FROM f.DATE_EMISSION);
/

/* Vue des travaux par entreprise pour un batiment (parties communes) */
CREATE OR REPLACE VIEW V_TRAVAUX_PAR_ENTREPRISE_BATIMENT AS
SELECT 
    f.ID_BATIMENT,
    b.ADRESSE AS ADRESSE_BATIMENT,
    e.NOM_ENTREPRISE,
    e.SIRET,
    EXTRACT(YEAR FROM f.DATE_EMISSION) AS ANNEE,
    SUM(f.MONTANT_TTC) AS TOTAL_TRAVAUX
FROM FACTURE f
JOIN ENTREPRISE e ON f.SIRET = e.SIRET
JOIN BATIMENT b ON f.ID_BATIMENT = b.ID_BATIMENT
WHERE (f.TRAVAUX IS NOT NULL OR f.DEDUCTIBLE_IMPOT = 1)
AND f.ID_LOGEMENT IS NULL
GROUP BY f.ID_BATIMENT, b.ADRESSE, e.NOM_ENTREPRISE, e.SIRET, 
         EXTRACT(YEAR FROM f.DATE_EMISSION);
/

COMMIT;

/* FIN DU SCRIPT 03_VUES.sql */
